export enum Permission {
  DASHBOARD = 'dashboard-index',
  ORGANIZATION_INDEX = 'organization-index',
  USER_INDEX = 'user-index',
  ROLE_INDEX = 'role-index',
  PERMISSION_INDEX = 'permission-index',
  AUDITORIUM_INDEX = 'auditorium-index',
  AUDITORIUM_EVENT_INDEX = 'auditorium-event-index',
  LIFE_GROUP_INDEX = 'life-group-index',
  STORE_INDEX = 'store-index',
  PRODUCT_INDEX = 'product-index',
  SALE_INDEX = 'sale-index',
  POS_KDS = 'pos-kds',
  EXPENSE_TICKET_INDEX = 'expense-ticket-index',
  TESTIMONY_INDEX = 'testimony-index',
  SONG_INDEX = 'song-index',
  CHURCH_EVENT_INDEX = 'church-event-index',
  CONSO_SHEET_INDEX = 'conso-sheet-index',
  CHURCH_MEMBER_CONSOLIDATOR_LOGS_INDEX = 'church-member-consolidator-logs-index',
  CHURCH_MEMBER_TRACKING_LOGS_INDEX = 'church-member-tracking-logs-index',
  CHURCH_MEMBER_TRACKING_LOGS_ALL = 'church-member-tracking-logs-all',
  WHATSAPP_INDEX = 'whatsapp-index',
  UKELELE_COURSE = 'ukelele-course',
  SING_COURSE = 'sing-course',
  BREATH_TRAIN = 'breath-train',
  PITCH_TRAIN = 'pitch-train',
}

export const PERMISSION_LABELS: Record<Permission, string> = {
  [Permission.DASHBOARD]: 'Dashboard',
  [Permission.ORGANIZATION_INDEX]: 'Organizaciones',
  [Permission.USER_INDEX]: 'Usuarios',
  [Permission.ROLE_INDEX]: 'Roles',
  [Permission.PERMISSION_INDEX]: 'Permisos',
  [Permission.AUDITORIUM_INDEX]: 'Auditorio',
  [Permission.AUDITORIUM_EVENT_INDEX]: 'Eventos de Auditorio',
  [Permission.LIFE_GROUP_INDEX]: 'Redes de Vida',
  [Permission.STORE_INDEX]: 'Tiendas',
  [Permission.PRODUCT_INDEX]: 'Productos',
  [Permission.SALE_INDEX]: 'Ventas',
  [Permission.POS_KDS]: 'Pantalla de Cocina',
  [Permission.EXPENSE_TICKET_INDEX]: 'Ticket de Gastos',
  [Permission.TESTIMONY_INDEX]: 'Testimonios',
  [Permission.SONG_INDEX]: 'Cancionero',
  [Permission.CHURCH_EVENT_INDEX]: 'Eventos Iglesia',
  [Permission.CONSO_SHEET_INDEX]: 'Consolidación',
  [Permission.CHURCH_MEMBER_CONSOLIDATOR_LOGS_INDEX]: 'Historial Consolidadores',
  [Permission.CHURCH_MEMBER_TRACKING_LOGS_INDEX]: 'Mi Actividad',
  [Permission.CHURCH_MEMBER_TRACKING_LOGS_ALL]: 'Actividad General',
  [Permission.WHATSAPP_INDEX]: 'WhatsApp',
  [Permission.UKELELE_COURSE]: 'Ukelele',
  [Permission.SING_COURSE]: 'Canto',
  [Permission.BREATH_TRAIN]: 'Relax',
  [Permission.PITCH_TRAIN]: 'Tuner',
}
